files_unchanged:
  - .github/ISSUE_TEMPLATE/bug_report.md
  - .github/ISSUE_TEMPLATE/feature_request.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - assets/nf-core-sarek_logo.png
  - docs/images/nf-core-sarek_logo.png
